//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShopManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddBook
    {
        public int Tracking_ID { get; set; }
        public string Book_Title { get; set; }
        public string Author { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Publisher { get; set; }
        public string Category { get; set; }
        public string Cost_Price { get; set; }
        public string Selling_Price { get; set; }
        public string Remarks { get; set; }
    }
}
